### ISSUE TITLE
Donation bot seems to be down

### ISSUE THREAD

**Issue by qwwdfsad** [PolarNick239/ArthasDonationsBot#2]
It seems like the bot is down and "Микроботыч" telegram bot is silent for the last two weeks, even though we still observe occasional streams on YouTube

**Comment by PgLoLo** [comment]
Hi @qwwdfsad  ! I'm an engineer at Микроботыч ИНК. I will look into this and get back to you!

Could you also provide a code snippet to recreate the error?

**Comment by PolarNick239** [comment]
Hi, I will report this information to our Investigation Department and if this problem will be reproduced on our side (on our telegram accounts) - they will escalate the problem to responsible colleagues in our Debugging Department.

**Comment by qwwdfsad** [comment]
@PgLoLo  Sure, I have a reproducing project.

You first have to `git clone https://github.com/PolarNick239/ArthasDonationsBot` and then just execute `run.sh` from the working directory.

**Comment by PolarNick239** [comment]
@qwwdfsad should it be executed under sudo?

**Comment by qwwdfsad** [comment]
Yes, I would even suggest you running it with `$USER ALL=(ALL) NOPASSWD: ALL` to avoid configuration errors with OpenCV

**Comment by PolarNick239** [comment]
Thanks for providing additional information, we will be back as soon as new information will be available.

**Comment by PgLoLo** [comment]
@qwwdfsad can you please check pull request?

**Comment by PolarNick239** [comment]
Yes, of course.

**Comment by PolarNick239** [comment]
@qwwdfsad have you already checked PR?

**Comment by qwwdfsad** [comment]
The bot is up, but unfortunately, I cannot properly review the PR as I have another job to do.

I've skimmed through it though and it seems that the biggest downside of the proposed fix is the fact that it is written in the Python

**Comment by PgLoLo** [comment]
> The bot is up, but unfortunately, I cannot properly review the PR as I have another job to do.
> 
> I've skimmed through it though and it seems that the biggest downside of the proposed fix is the fact that it is written in the Python

Would you recommend rewriting in C++?

PolarNick239: edited - C++ starts with capital letter
